/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.sound.sampled.*;
import java.io.*;
import javax.swing.filechooser.*;
import controller.ControllerFeed;
import model.Usuario;

/**
 *
 * @author leona
 */
public class Feed extends javax.swing.JFrame{
    private Usuario usuario;
    private String getCoisa;

    /**
     *
     * @return
     */
    public String getGetCoisa() {
        return getCoisa;
    }
    
//    private JTextField filePathField;
//    private JButton playButton;
//    private JButton pauseButton;
//    private JButton chooseButton;
//    private JButton loopButton;
//    private boolean isPaused;
//    private boolean isLooping = false;
//    private JFileChooser fileChooser;
//    private Clip clip;
    /**
     * Creates new form Feed
     */
    ControllerFeed c = new ControllerFeed(this);

    /**
     *
     */
    public Feed() {
        initComponents();
        String path1 = "src/img/like.png"; 
        ImageIcon ic1= new ImageIcon(path1);
        Image nw1 = ic1.getImage().getScaledInstance(50, 40, Image.SCALE_AREA_AVERAGING);
        ImageIcon scaledIcon1 = new ImageIcon(nw1);

        curtir_botao.setIcon(scaledIcon1);
        String path2 = "src/img/dislike.png"; 
        ImageIcon ic2 = new ImageIcon(path2);
        Image nw2 = ic2.getImage().getScaledInstance(50, 40, Image.SCALE_AREA_AVERAGING);
        ImageIcon scaledIcon2 = new ImageIcon(nw2);

        descurtir_botao.setIcon(scaledIcon2);
//        c.clickarMusica();
        SwingUtilities.invokeLater(() -> {
//            c.clickarMusica();
            //c.carregarMusica();
        });
        
        setResizable(true);
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/spotifei3-removebg-preview.png")));
        
        GraphicsDevice device  = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        device.setFullScreenWindow(this);
        //outerPanel.setLayout(new BoxLayout(outerPanel, BoxLayout.Y_AXIS));
        JPanel panel1 = new JPanel();
        
        panel1.setPreferredSize(new Dimension(1550, 830));  // Define o tamanho preferido

        // Caso esteja usando layout nulo, pode definir diretamente o tamanho
        panel1.setSize(1550, 830);  // Define o tamanho real
        
   
        
    }

    /**
     *
     * @return
     */
    public Usuario getUsuario() {
        return usuario;
    }
        
    /**
     *
     * @param usuario
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;

        // Exemplo: mostrar o nome de usuário no console ou em um label
        System.out.println("Usuário logado: " + usuario.getUsuario());

        // ou exibir em uma label, se quiser:
        // lblUsuario.setText("Bem-vindo, " + usuario.getUsuario());
    }

    /**
     *
     * @return
     */
    public JPanel getPainelPrincipal() {

        return painelPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelPrincipal = new javax.swing.JPanel();
        painel_inicial = new javax.swing.JPanel();
        dez_ultimas = new javax.swing.JButton();
        musicas_curtidas = new javax.swing.JButton();
        musicas_descurtidas = new javax.swing.JButton();
        nova_playlist = new javax.swing.JButton();
        buscaTexto = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        botao_busca = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        curtir_botao = new javax.swing.JButton();
        descurtir_botao = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1550, 830));
        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 830));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(null);

        painelPrincipal.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        jPanel1.add(painelPrincipal);
        painelPrincipal.setBounds(0, 60, 410, 710);

        painel_inicial.setBackground(new java.awt.Color(51, 51, 51));

        dez_ultimas.setText("Veja as 10 últimas músicas buscadas");
        dez_ultimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dez_ultimasActionPerformed(evt);
            }
        });

        musicas_curtidas.setText("Visualizar Lista de músicas curtidas");
        musicas_curtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicas_curtidasActionPerformed(evt);
            }
        });

        musicas_descurtidas.setText("Visualizar Lista de músicas descurtidas");
        musicas_descurtidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicas_descurtidasActionPerformed(evt);
            }
        });

        nova_playlist.setText("Carregar Playlists / Nova Playlist +");
        nova_playlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nova_playlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_inicialLayout = new javax.swing.GroupLayout(painel_inicial);
        painel_inicial.setLayout(painel_inicialLayout);
        painel_inicialLayout.setHorizontalGroup(
            painel_inicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_inicialLayout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addGroup(painel_inicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(nova_playlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(musicas_descurtidas, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(musicas_curtidas, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                    .addComponent(dez_ultimas, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addGap(216, 216, 216))
        );
        painel_inicialLayout.setVerticalGroup(
            painel_inicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_inicialLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(nova_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dez_ultimas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(musicas_curtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(musicas_descurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
        );

        jPanel1.add(painel_inicial);
        painel_inicial.setBounds(420, 60, 1110, 710);

        buscaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaTextoActionPerformed(evt);
            }
        });
        jPanel1.add(buscaTexto);
        buscaTexto.setBounds(610, 10, 410, 40);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(503, 0, 70, 60);

        botao_busca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        botao_busca.setBorder(null);
        botao_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_buscaActionPerformed(evt);
            }
        });
        jPanel1.add(botao_busca);
        botao_busca.setBounds(1030, 10, 30, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("DELETAR MÚSICA");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(230, 780, 180, 50);

        curtir_botao.setBackground(new java.awt.Color(0, 102, 0));
        curtir_botao.setBorder(null);
        curtir_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curtir_botaoActionPerformed(evt);
            }
        });
        jPanel1.add(curtir_botao);
        curtir_botao.setBounds(760, 780, 90, 50);

        descurtir_botao.setBackground(new java.awt.Color(204, 0, 0));
        descurtir_botao.setBorder(null);
        descurtir_botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descurtir_botaoActionPerformed(evt);
            }
        });
        jPanel1.add(descurtir_botao);
        descurtir_botao.setBounds(870, 780, 100, 50);

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("DELETAR PLAYLIST");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 780, 170, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 1550, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @return
     */
    public JTextField getBuscaTexto() {
        return buscaTexto;
    }

    private void buscaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaTextoActionPerformed
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
//        c.limpaMusica();
        for (Component todos : painel_inicial.getComponents()) {
            todos.setVisible(false);
        }
        
        nova_playlist.setVisible(true);
        dez_ultimas.setVisible(true);
        musicas_curtidas.setVisible(true);
        musicas_descurtidas.setVisible(true);
        
        painel_inicial.add(nova_playlist);
        painel_inicial.add(dez_ultimas);
        painel_inicial.add(musicas_curtidas);
        painel_inicial.add(musicas_descurtidas);
//        painel_inicial.revalidate();
//        painel_inicial.repaint();
//        nova_playlist.setVisible(true);
//        dez_ultimas.setVisible(true);
//        musicas_curtidas.setVisible(true);
//        musicas_descurtidas.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void dez_ultimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dez_ultimasActionPerformed
        c.exibirDezUltimasMusicasBuscadas();
    }//GEN-LAST:event_dez_ultimasActionPerformed

    private void musicas_curtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicas_curtidasActionPerformed
        c.exibirMusicasCurtidas();
    }//GEN-LAST:event_musicas_curtidasActionPerformed

    private void musicas_descurtidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicas_descurtidasActionPerformed
        c.exibirMusicasDescurtidas();
    }//GEN-LAST:event_musicas_descurtidasActionPerformed

    private void nova_playlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nova_playlistActionPerformed
        c.novaPlaylist();
    }//GEN-LAST:event_nova_playlistActionPerformed

    private void botao_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_buscaActionPerformed
        c.buscarMusica();
    }//GEN-LAST:event_botao_buscaActionPerformed

    private void curtir_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtir_botaoActionPerformed

        c.curtir();
    }//GEN-LAST:event_curtir_botaoActionPerformed

    private void descurtir_botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descurtir_botaoActionPerformed

        c.descurtir();
    }//GEN-LAST:event_descurtir_botaoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        c.deletarPlaylist();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        c.deletarMusicaDaPlaylist();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *
     * @return
     */
    public JPanel getPainel_inicial() {
        return painel_inicial;
    }

    /**
     *
     * @return
     */
    public JButton getDez_ultimas() {
        return dez_ultimas;
    }

    /**
     *
     * @return
     */
    public JButton getMusicas_curtidas() {
        return musicas_curtidas;
    }

    /**
     *
     * @return
     */
    public JButton getMusicas_descurtidas() {
        return musicas_descurtidas;
    }

    /**
     * @return 
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Feed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Feed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Feed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Feed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new Feed();
//                new Feed().setVisible(true);
//            }
//        });
//    }

    public JButton getNova_playlist() {
        return nova_playlist;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_busca;
    private javax.swing.JTextField buscaTexto;
    private javax.swing.JButton curtir_botao;
    private javax.swing.JButton descurtir_botao;
    private javax.swing.JButton dez_ultimas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton musicas_curtidas;
    private javax.swing.JButton musicas_descurtidas;
    private javax.swing.JButton nova_playlist;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painel_inicial;
    // End of variables declaration//GEN-END:variables
}
